export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAILED = 'IMAGE_LIST_FAILED';


export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAILED = 'ADD_IMAGE_FAILED';


export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_FAILED = 'UPDATE_IMAGE_FAILED';


export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILED = 'DELETE_IMAGE_FAILED';